In [ ]:
#10. Матрицы.
#• Сгенерировать две случайные матрицы заданного размера.
#• Вычислить сумму, произведение, определитель и обратные матрицы.
#• Реализовать сохранение матриц в файл.
#• Добавить вариант со считыванием матриц из файла.
#• Выбор формата обосновать, привести плюсы и минусы.
#• Что нужно сделать, чтобы добавить поддержку матриц комплексных чисел?
#• Измерить время обращения матриц 10x10, 100x100, 1000x1000

import numpy as np
from numpy.random import randint as rndm

In [2]:
#• Сгенерировать две случайные матрицы заданного размера.

am, an = 2, 2
A = rndm(0, 10, (am,an))
print(A)

print('\n')

bm, bn = 2, 2
B = rndm(0, 10, (bm, bn))
print(B)

[[2 4]
 [9 1]]


[[6 1]
 [0 3]]


In [3]:
#• Вычислить сумму, произведение, определитель и обратные матрицы.

print(f"A+B =\n {A+B}\n")
print(f"AB =\n {A@B}\n")
print(f"|A|={np.linalg.det(A)}\n|B|={np.linalg.det(B)}\n")
print(f"A^-1 =\n {np.linalg.inv(A)}\nB^-1 =\n {np.linalg.inv(B)}\n")

A+B =
 [[8 5]
 [9 4]]

AB =
 [[12 14]
 [54 12]]

|A|=-34.00000000000001
|B|=17.999999999999996

A^-1 =
 [[-0.02941176  0.11764706]
 [ 0.26470588 -0.05882353]]
B^-1 =
 [[ 0.16666667 -0.05555556]
 [ 0.          0.33333333]]



In [12]:
#• Реализовать сохранение матриц в файл.

with open('D:\\python\\txtfiles\\matrices_output.txt', 'w') as f:
    f.write(f"A+B =\n {A+B}\n\n")
    f.write(f"AB =\n {A@B}\n\n")
    f.write(f"|A|={np.linalg.det(A)}\n|B|={np.linalg.det(B)}\n\n")
    f.write(f"A^-1 =\n {np.linalg.inv(A)}\n\nB^-1 =\n {np.linalg.inv(B)}\n")

In [1]:
#• Добавить вариант со считыванием матриц из файла.
#плюсы формата: это быстро пишется
#минусы формата: нужно писать данные в разные файлы

A1 = np.loadtxt('D:\\python\\txtfiles\\matrix_A_input.txt')
print(f"{Ac}\n")

B1 = np.loadtxt('D:\\python\\txtfiles\\matrix_B_input.txt')
print(f"{Bc}\n")

print(f"A+B =\n {A1+B1}\n")
print(f"AB =\n {A1@B1}\n")
print(f"|A|={np.linalg.det(A1)}\n|B|={np.linalg.det(B1)}\n")
print(f"A^-1 =\n {np.linalg.inv(A1)}\nB^-1 =\n {np.linalg.inv(B1)}\n")

In [88]:
#• Что нужно сделать, чтобы добавить поддержку матриц комплексных чисел?
#numpy-матрицы вообще работают только с фиксированным типом, максимум - плавающая точка
#нужно определить тип массива
#но rndm не поддерживает этот тип

Ac = np.array([[1+3j , 3+1j], [11+6j , 1-7j]], np.complex)
Bc = np.array([[4-4j , 9+7j], [146-1j , 3-1j]], np.complex)
print(f"{Ac}\n")
print(f"{Bc}\n")

print('\n')

print(f"A+B =\n {Ac+Bc}\n")
print(f"AB =\n {Ac@Bc}\n")
print(f"|A|={np.linalg.det(Ac)}\n|B|={np.linalg.det(Bc)}\n")
print(f"A^-1 =\n {np.linalg.inv(Ac)}\nB^-1 =\n {np.linalg.inv(Bc)}\n")

#help(rndm)
#ну, работает

[[ 1.+3.j  3.+1.j]
 [11.+6.j  1.-7.j]]

[[  4.-4.j   9.+7.j]
 [146.-1.j   3.-1.j]]



A+B =
 [[  5.-1.j  12.+8.j]
 [157.+5.j   4.-8.j]]

AB =
 [[455. +151.j  -2.  +34.j]
 [207.-1043.j  53. +109.j]]

|A|=(-4.999999999999995-32.99999999999999j)
|B|=(-1313.0000000000011-1029.0000000000011j)

A^-1 =
 [[ 0.20287253+0.06104129j  0.04308797-0.08438061j]
 [ 0.22710952-0.2989228j  -0.09335727+0.01615799j]]
B^-1 =
 [[-0.00104571+1.58113561e-03j  0.00683482-2.51544302e-05j]
 [ 0.06851672-5.44582634e-02j -0.00040822+3.36638146e-03j]]



In [41]:
#• Измерить время обращения матриц 10x10, 100x100, 1000x1000.
import time

atm, atn = 1000, 1000
At = rndm(0, 10, (atm,atn))

t1 = time.time()
At1 = np.linalg.inv(At)
t2 = time.time()

print(f"dt = {t2-t1}")

dt = 0.1620790958404541
